version: "3.8"

services:
  backend:
    build: .
    container_name: job_portal_backend
    restart: always
    expose:
      - "3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/job_portal
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  mongo-data:
